# Generated by Django 3.1.7 on 2021-04-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210404_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
    ]
