# Generated by Django 3.1.7 on 2021-04-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210407_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['-id'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографії'},
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок питаня'),
        ),
    ]
